name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pytest
        coverage run -m pytest
        coverage xml
  deploy:
    name: Deploying app
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, 'bump version')"
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Build and push image to Google Container Registry
      - name: Setting up
        uses: google-github-actions/setup-gcloud@master
        with:
          version: '286.0.0'
          service_account_key: ${{ secrets.GCP_SA_KEY_JSON }}
          service_account_email: "EMAIL"
          project_id: PROJECT_ID

      - name: Building (🏗)
        run: |-
          gcloud builds submit \
            --tag gcr.io/PROJECT_ID/SERVICE_ID

      # Setup gcloud CLI
      - name: Deploy (🚀)
        uses: google-github-actions/deploy-cloudrun@main
        with:
          service: SERVICE_ID
          image: gcr.io/PROJECT_ID/SERVICE_ID
          region: REGION
          credentials: ${{ secrets.GCP_SA_KEY_JSON }}
          project_id: PROJECT_ID

